import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const STORAGE_KEY = 'campusevents-language';

const translations = {
  en: {
    appName: 'KFUPMEvents',
    brandSubtitle: 'King Fahd University',
    events: 'Events',
    myTickets: 'My Tickets',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
    signIn: 'Sign In',
    signOut: 'Sign out',
    attendeeAccount: 'Attendee Account',
    organizerAccount: 'Organizer Account',
    adminAccount: 'Admin Account',
    attendee: 'Attendee',
    organizer: 'Organizer',
    admin: 'Admin',
    allEvents: 'All Events',
    workshops: 'Workshops',
    career: 'Career',
    cultural: 'Cultural',
    competition: 'Competition',
    sports: 'Sports',
    seminar: 'Seminar',
    joinUs: 'Join Us',
    heroKicker: 'Saudi concert calendar',
    heroTitle: "What's concert happening in Saudi?",
    searchByEventVenue: 'Search by event, club, venue',
    searchPlaceholder: 'AI workshop, career fair, sports day...',
    category: 'Category',
    allCategories: 'All Categories',
    selectDate: 'Select Date',
    search: 'Search',
    featuredEvent: 'Featured Event',
    filters: 'Filters:',
    searchByTitle: 'Search by title or tag',
    noEventsFound: 'No events found',
    noEventsHint: 'Try clearing filters or using another keyword.',
    browsingEventsIn: 'Browsing Events In',
    allVenues: 'All Venues',
    today: 'Today',
    thisWeekend: 'This Weekend',
    thisMonth: 'This Month',
    festival: 'Festival',
    findTickets: 'Find Tickets',
    eventBrowser: 'Event browser',
    previousEvents: 'Previous events',
    nextEvents: 'Next events',
    seatsAvailable: 'seats available',
    registered: 'registered',
    viewDetails: 'View Details',
    organizedBy: 'Organized by',
    eventNotAvailable: 'Event not available',
    backToEvents: 'Back to Events',
    of: 'of',
    aboutThisEvent: 'About This Event',
    eventTags: 'Event Tags',
    eventPolicy: 'Event Policy',
    registrationCloses: 'Registration closes:',
    cancellationDeadline: 'Cancellation deadline:',
    youreRegistered: "You're registered!",
    viewMyTicket: 'View My Ticket',
    seatsLeft: 'seats left',
    agreePolicy: 'I agree to event rules and cancellation policy',
    bookTicket: 'Book Ticket',
    attendeeOnlyBooking: 'Booking is available for attendee accounts only.',
    signInToBook: 'Sign in with an attendee account to book this event.',
    addToCalendar: 'Add to Calendar',
    shareEvent: 'Share Event',
    onlyAttendeesReserve: 'Only attendee accounts can reserve tickets.',
    agreePolicyError: 'Please agree to the event rules and cancellation policy.',
    limitReached: 'Per-user limit reached for this event.',
    eventFull: 'This event is full.',
    signInFirst: 'Please sign in first.',
    bookingNotOpen: 'Event is not open for booking yet.',
    bookingFailed: 'Booking failed.',
    calendarDownloaded: 'Calendar file downloaded.',
    eventShared: 'Event shared.',
    eventLinkCopied: 'Event link copied.',
    sharingCancelled: 'Sharing was cancelled.',
    upcoming: 'Upcoming',
    past: 'Past',
    cancelled: 'Cancelled',
    noTicketsFound: 'No tickets found',
    noTicketsHint: 'You do not have any events in this tab.',
    browseEvents: 'Browse Events',
    ticket: 'ticket',
    tickets: 'tickets',
    viewQrCode: 'View QR Code',
    cancelTicket: 'Cancel Ticket',
    ticketNotFound: 'Ticket not found',
    backToMyTickets: 'Back to My Tickets',
    yourTicket: 'Your Ticket',
    closeTicketView: 'Close ticket view',
    at: 'at',
    presentQr: 'Present this QR code at the event entrance for check-in',
    downloadTicket: 'Download Ticket',
    ticketDownloaded: 'Ticket downloaded.',
    adminDashboard: 'Admin Dashboard',
    adminSubtitle: 'Manage events, users, and organizer applications',
    pendingEvents: 'Pending Events',
    pendingApplications: 'Pending Applications',
    totalUsers: 'Total Users',
    allEventsStat: 'All Events',
    eventReviews: 'Event Reviews',
    allEventsTab: 'All Events',
    organizerApplications: 'Organizer Applications',
    userManagement: 'User Management',
    event: 'Event',
    date: 'Date',
    capacity: 'Capacity',
    actions: 'Actions',
    status: 'Status',
    registrations: 'Registrations',
    applicant: 'Applicant',
    organization: 'Organization',
    type: 'Type',
    submitted: 'Submitted',
    approve: 'Approve',
    reject: 'Reject',
    delete: 'Delete',
    user: 'User',
    kfupmId: 'KFUPM ID',
    role: 'Role',
    searchUsersPlaceholder: 'Search users by name or email...',
    ban: 'Ban',
    unban: 'Unban',
    organizerDashboard: 'Organizer Dashboard',
    organizerDashboardSubtitle: 'Manage your events, approvals, registrations, and drafts.',
    activeEvents: 'Active Events',
    pendingApproval: 'Pending Approval',
    totalRegistrations: 'Total Registrations',
    drafts: 'Drafts',
    createNewEvent: 'Create New Event',
    myEvents: 'My Events',
    submit: 'Submit',
    editEvent: 'Edit Event',
    basicInfo: 'Basic Info',
    schedule: 'Schedule',
    review: 'Review',
    eventTitle: 'Event Title',
    shortDescription: 'Short Description',
    longDescription: 'Long Description',
    time: 'Time',
    location: 'Location',
    locationPlaceholder: 'Building/Room or Online link',
    visibility: 'Visibility',
    eventMode: 'Event Mode',
    university: 'University',
    public: 'Public',
    offline: 'Offline',
    online: 'Online',
    hybrid: 'Hybrid',
    perUserLimit: 'Per-user Limit',
    priceType: 'Price Type',
    free: 'Free',
    paid: 'Paid',
    coverTheme: 'Cover Theme',
    eventPicture: 'Event Picture',
    uploadCoverHint: 'Upload a cover image for this event card and details page.',
    tags: 'Tags',
    tagsPlaceholder: 'AI, Campus, Workshop',
    saveDraft: 'Save Draft',
    previous: 'Previous',
    next: 'Next',
    submitForApproval: 'Submit for Approval',
    untitledEvent: 'Untitled event',
    addShortDescription: 'Add a short description.',
    setLocation: 'Set a location',
    eventNotFound: 'Event not found.',
    registrationsCheckIn: 'Organizer - Registrations & Check-in',
    scanQr: 'Scan QR',
    exportCsv: 'Export CSV',
    searchAttendeePlaceholder: 'Search attendee by name / ID / ticket code',
    name: 'Name',
    universityId: 'University ID',
    action: 'Action',
    checkedIn: 'Checked-in',
    notIn: 'Not in',
    done: 'Done',
    checkIn: 'Check-in',
    scanTickets: 'Scan Tickets',
    ticketScanner: 'Ticket Scanner',
    ticketScannerSubtitle: 'Scan a ticket QR code or enter the ticket code manually to validate entry.',
    scannerEvent: 'Scanner Event',
    allOrganizerEvents: 'All My Events',
    allManagedEvents: 'All Managed Events',
    startCamera: 'Start Camera',
    stopCamera: 'Stop Camera',
    scanReady: 'Ready to scan',
    scanReadyHint: 'Point the camera at the ticket QR code or use the manual code field below.',
    manualTicketCode: 'Manual Ticket Code',
    manualTicketPlaceholder: 'TKT-AI-2026-001',
    verifyAndCheckIn: 'Verify & Check In',
    demoTicketCodes: 'Demo ticket codes',
    waitingForScan: 'Waiting for scan',
    scanTicket: 'Scan Ticket',
    validTicket: 'Valid Ticket',
    invalidTicket: 'Invalid Ticket',
    checkedInNow: 'Checked In',
    alreadyCheckedIn: 'Already Checked In',
    ticketDetails: 'Ticket Details',
    recentScans: 'Recent Scans',
    noScansYet: 'No scans yet.',
    emptyTicketCode: 'Enter a ticket code.',
    ticketNotFoundScan: 'No ticket matches this code.',
    ticketNotAllowed: 'This ticket belongs to another organizer event.',
    wrongEventTicket: 'This ticket is valid, but not for the selected event.',
    cancelledTicketScan: 'This ticket is cancelled.',
    ticketScanInvalid: 'Ticket scan failed.',
    ticketAlreadyCheckedIn: 'Ticket already checked in.',
    scanSourceManual: 'Checked with manual code.',
    scanSourceCamera: 'Checked with camera scan.',
    cameraNotSupported: 'Camera access is not supported in this browser.',
    barcodeNotSupported: 'This browser cannot scan QR codes from the camera. Use the manual ticket code instead.',
    cameraPermissionDenied: 'Camera permission was denied or the camera could not be started.',
    scannerCameraReadError: 'Camera scanner stopped because the QR reader could not process the video.',
    organizerApplication: 'Organizer Application',
    organizerApplicationSubtitle: 'For clubs, departments, and university units that want to publish events.',
    organizationName: 'Organization Name',
    officialEmail: 'Official Email',
    advisorName: 'Supervisor / Advisor Name',
    verificationDocument: 'Verification Document',
    createPassword: 'Create a password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    notes: 'Notes',
    cancel: 'Cancel',
    requiredFields: 'Please fill in all required fields.',
    pdfRequired: 'Verification document must be a PDF file.',
    passwordMismatch: 'Password confirmation does not match.',
    club: 'Club',
    department: 'Department',
    unit: 'Unit',
    technology: 'Technology',
    loginTitle: 'Sign in to KFUPMEvents',
    loginSubtitle: 'Use your KFUPM credentials to continue',
    kfupmEmail: 'KFUPM Email',
    emailPlaceholder: 'your.name@kfupm.edu.sa',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    universityAccount: 'Use your university account',
    forgotPassword: 'Forgot password?',
    passwordResetSoon: 'Password reset link will be available after backend integration.',
    quickDemoLogin: 'Quick Demo Login',
    loginAsAttendee: 'Login as Attendee',
    loginAsOrganizer: 'Login as Organizer',
    loginAsAdmin: 'Login as Admin',
    organizerApplyCta: 'New organizer? Apply for organizer privileges',
    invalidEmail: 'Enter a valid KFUPM email address.',
    weakPassword: 'Password must be at least 8 characters and include letters and numbers.',
    noAccountFound: 'No account was found for this email.',
    accountDisabled: 'This account is currently disabled.',
    invalidCredentials: 'Invalid email or password.',
    signedInSuccessfully: 'Signed in successfully.',
    signedInAs: 'Signed in as',
    ticketReserved: 'Ticket reserved successfully.',
    bookingCancelled: 'Booking cancelled.',
    eventUpdated: 'Event updated.',
    draftSaved: 'Draft saved.',
    eventSubmitted: 'Event submitted for approval.',
    eventApproved: 'Event approved.',
    eventRejected: 'Event rejected.',
    eventDeleted: 'Event deleted.',
    applicationApproved: 'Application approved.',
    applicationRejected: 'Application rejected.',
    adminCannotDemote: 'Admin cannot demote the active account.',
    userRoleUpdated: 'User role updated.',
    adminCannotBanSelf: 'Admin cannot ban the active account.',
    userStatusUpdated: 'User status updated.',
    organizerApplicationSubmitted: 'Organizer application submitted.',
    checkedInSuccess: 'Checked-in successfully (time recorded).',
    view: 'View',
    edit: 'Edit',
    menu: 'Menu',
    eventShortcuts: 'Event shortcuts',
    openMenu: 'Open menu',
    switchLanguage: 'Switch language',
    imageFileError: 'Please choose an image file for the event cover.',
    completeBasicInfo: 'Complete all required basic information fields.',
    completeSchedule: 'Complete all required schedule fields.',
    completeTicketPolicy: 'Capacity, per-user limit, and event policy are required.'
  },
  ar: {
    appName: 'فعاليات جامعة الملك فهد',
    brandSubtitle: 'جامعة الملك فهد',
    events: 'الفعاليات',
    myTickets: 'تذاكري',
    dashboard: 'لوحة التحكم',
    adminPanel: 'لوحة الإدارة',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    attendeeAccount: 'حساب حاضر',
    organizerAccount: 'حساب منظم',
    adminAccount: 'حساب مدير',
    attendee: 'حاضر',
    organizer: 'منظم',
    admin: 'مدير',
    allEvents: 'كل الفعاليات',
    workshops: 'ورش العمل',
    career: 'المسار المهني',
    cultural: 'ثقافية',
    competition: 'مسابقات',
    sports: 'رياضة',
    seminar: 'ندوات',
    joinUs: 'انضم لنا',
    heroKicker: 'تقويم فعاليات جامعة الملك فهد',
    heroTitle: 'ايش احداث جامعة الملك فهد القادمة',
    searchByEventVenue: 'ابحث باسم الفعالية أو النادي أو المكان',
    searchPlaceholder: 'ورشة ذكاء اصطناعي، يوم المهنة، يوم رياضي...',
    category: 'التصنيف',
    allCategories: 'كل التصنيفات',
    selectDate: 'اختر التاريخ',
    search: 'بحث',
    featuredEvent: 'فعالية مميزة',
    filters: 'الفلاتر:',
    searchByTitle: 'ابحث بالعنوان أو الوسم',
    noEventsFound: 'لا توجد فعاليات',
    noEventsHint: 'جرّب إزالة الفلاتر أو استخدام كلمة أخرى.',
    browsingEventsIn: 'استعراض الفعاليات في',
    allVenues: 'كل المواقع',
    today: 'اليوم',
    thisWeekend: 'نهاية الأسبوع',
    thisMonth: 'هذا الشهر',
    festival: 'مهرجان',
    findTickets: 'احجز تذكرتك',
    eventBrowser: 'متصفح الفعاليات',
    previousEvents: 'الفعاليات السابقة',
    nextEvents: 'الفعاليات التالية',
    seatsAvailable: 'مقاعد متاحة',
    registered: 'مسجل',
    viewDetails: 'عرض التفاصيل',
    organizedBy: 'تنظيم',
    eventNotAvailable: 'الفعالية غير متاحة',
    backToEvents: 'العودة للفعاليات',
    of: 'من',
    aboutThisEvent: 'عن الفعالية',
    eventTags: 'وسوم الفعالية',
    eventPolicy: 'سياسة الفعالية',
    registrationCloses: 'يغلق التسجيل:',
    cancellationDeadline: 'آخر موعد للإلغاء:',
    youreRegistered: 'تم تسجيلك!',
    viewMyTicket: 'عرض تذكرتي',
    seatsLeft: 'مقاعد متبقية',
    agreePolicy: 'أوافق على قواعد الفعالية وسياسة الإلغاء',
    bookTicket: 'حجز تذكرة',
    attendeeOnlyBooking: 'الحجز متاح لحسابات الحضور فقط.',
    signInToBook: 'سجّل الدخول بحساب حاضر لحجز هذه الفعالية.',
    addToCalendar: 'إضافة للتقويم',
    shareEvent: 'مشاركة الفعالية',
    onlyAttendeesReserve: 'حسابات الحضور فقط يمكنها حجز التذاكر.',
    agreePolicyError: 'يرجى الموافقة على قواعد الفعالية وسياسة الإلغاء.',
    limitReached: 'تم الوصول إلى حد الحجز لهذه الفعالية.',
    eventFull: 'هذه الفعالية ممتلئة.',
    signInFirst: 'يرجى تسجيل الدخول أولاً.',
    bookingNotOpen: 'الحجز غير متاح لهذه الفعالية حالياً.',
    bookingFailed: 'فشل الحجز.',
    calendarDownloaded: 'تم تحميل ملف التقويم.',
    eventShared: 'تمت مشاركة الفعالية.',
    eventLinkCopied: 'تم نسخ رابط الفعالية.',
    sharingCancelled: 'تم إلغاء المشاركة.',
    upcoming: 'القادمة',
    past: 'السابقة',
    cancelled: 'الملغاة',
    noTicketsFound: 'لا توجد تذاكر',
    noTicketsHint: 'لا توجد لديك فعاليات في هذا التبويب.',
    browseEvents: 'تصفح الفعاليات',
    ticket: 'تذكرة',
    tickets: 'تذاكر',
    viewQrCode: 'عرض رمز QR',
    cancelTicket: 'إلغاء التذكرة',
    ticketNotFound: 'التذكرة غير موجودة',
    backToMyTickets: 'العودة إلى تذاكري',
    yourTicket: 'تذكرتك',
    closeTicketView: 'إغلاق عرض التذكرة',
    at: 'الساعة',
    presentQr: 'اعرض رمز QR عند مدخل الفعالية لتسجيل الحضور',
    downloadTicket: 'تحميل التذكرة',
    ticketDownloaded: 'تم تحميل التذكرة.',
    adminDashboard: 'لوحة الإدارة',
    adminSubtitle: 'إدارة الفعاليات والمستخدمين وطلبات المنظمين',
    pendingEvents: 'الفعاليات المعلقة',
    pendingApplications: 'الطلبات المعلقة',
    totalUsers: 'إجمالي المستخدمين',
    allEventsStat: 'كل الفعاليات',
    eventReviews: 'مراجعة الفعاليات',
    allEventsTab: 'كل الفعاليات',
    organizerApplications: 'طلبات المنظمين',
    userManagement: 'إدارة المستخدمين',
    event: 'الفعالية',
    date: 'التاريخ',
    capacity: 'السعة',
    actions: 'الإجراءات',
    status: 'الحالة',
    registrations: 'التسجيلات',
    applicant: 'مقدم الطلب',
    organization: 'الجهة',
    type: 'النوع',
    submitted: 'تاريخ التقديم',
    approve: 'قبول',
    reject: 'رفض',
    delete: 'حذف',
    user: 'المستخدم',
    kfupmId: 'الرقم الجامعي',
    role: 'الدور',
    searchUsersPlaceholder: 'ابحث بالاسم أو البريد...',
    ban: 'حظر',
    unban: 'إلغاء الحظر',
    organizerDashboard: 'لوحة المنظم',
    organizerDashboardSubtitle: 'إدارة الفعاليات والموافقات والتسجيلات والمسودات.',
    activeEvents: 'الفعاليات النشطة',
    pendingApproval: 'بانتظار الموافقة',
    totalRegistrations: 'إجمالي التسجيلات',
    drafts: 'المسودات',
    createNewEvent: 'إنشاء فعالية جديدة',
    myEvents: 'فعالياتي',
    submit: 'إرسال',
    editEvent: 'تعديل الفعالية',
    basicInfo: 'المعلومات الأساسية',
    schedule: 'الجدول',
    review: 'المراجعة',
    eventTitle: 'عنوان الفعالية',
    shortDescription: 'وصف مختصر',
    longDescription: 'وصف تفصيلي',
    time: 'الوقت',
    location: 'المكان',
    locationPlaceholder: 'المبنى/القاعة أو رابط الحضور',
    visibility: 'الظهور',
    eventMode: 'نمط الفعالية',
    university: 'الجامعة',
    public: 'عام',
    offline: 'حضوري',
    online: 'عن بعد',
    hybrid: 'هجين',
    perUserLimit: 'الحد لكل مستخدم',
    priceType: 'نوع السعر',
    free: 'مجاني',
    paid: 'مدفوع',
    coverTheme: 'سمة الغلاف',
    eventPicture: 'صورة الفعالية',
    uploadCoverHint: 'ارفع صورة غلاف تظهر في بطاقة الفعالية وصفحة التفاصيل.',
    tags: 'الوسوم',
    tagsPlaceholder: 'ذكاء اصطناعي، الحرم، ورشة',
    saveDraft: 'حفظ كمسودة',
    previous: 'السابق',
    next: 'التالي',
    submitForApproval: 'إرسال للموافقة',
    untitledEvent: 'فعالية بلا عنوان',
    addShortDescription: 'أضف وصفاً مختصراً.',
    setLocation: 'حدد المكان',
    eventNotFound: 'الفعالية غير موجودة.',
    registrationsCheckIn: 'التسجيلات وتسجيل الحضور',
    scanQr: 'مسح QR',
    exportCsv: 'تصدير CSV',
    searchAttendeePlaceholder: 'ابحث باسم الحاضر / الرقم / رمز التذكرة',
    name: 'الاسم',
    universityId: 'الرقم الجامعي',
    action: 'الإجراء',
    checkedIn: 'تم الحضور',
    notIn: 'لم يحضر',
    done: 'تم',
    checkIn: 'تسجيل حضور',
    scanTickets: 'مسح التذاكر',
    ticketScanner: 'ماسح التذاكر',
    ticketScannerSubtitle: 'امسح رمز QR للتذكرة أو أدخل رمز التذكرة يدويًا للتحقق من الدخول.',
    scannerEvent: 'فعالية المسح',
    allOrganizerEvents: 'كل فعالياتي',
    allManagedEvents: 'كل الفعاليات المدارة',
    startCamera: 'تشغيل الكاميرا',
    stopCamera: 'إيقاف الكاميرا',
    scanReady: 'جاهز للمسح',
    scanReadyHint: 'وجّه الكاميرا إلى رمز QR في التذكرة أو استخدم حقل الرمز اليدوي بالأسفل.',
    manualTicketCode: 'رمز التذكرة اليدوي',
    manualTicketPlaceholder: 'TKT-AI-2026-001',
    verifyAndCheckIn: 'تحقق وسجّل الحضور',
    demoTicketCodes: 'رموز تذاكر تجريبية',
    waitingForScan: 'بانتظار المسح',
    scanTicket: 'مسح تذكرة',
    validTicket: 'تذكرة صالحة',
    invalidTicket: 'تذكرة غير صالحة',
    checkedInNow: 'تم تسجيل الحضور',
    alreadyCheckedIn: 'تم تسجيلها مسبقًا',
    ticketDetails: 'تفاصيل التذكرة',
    recentScans: 'عمليات المسح الأخيرة',
    noScansYet: 'لا توجد عمليات مسح بعد.',
    emptyTicketCode: 'أدخل رمز التذكرة.',
    ticketNotFoundScan: 'لا توجد تذكرة بهذا الرمز.',
    ticketNotAllowed: 'هذه التذكرة تتبع فعالية لمنظم آخر.',
    wrongEventTicket: 'التذكرة صالحة، لكنها ليست للفعالية المحددة.',
    cancelledTicketScan: 'هذه التذكرة ملغاة.',
    ticketScanInvalid: 'فشل مسح التذكرة.',
    ticketAlreadyCheckedIn: 'تم تسجيل حضور هذه التذكرة مسبقًا.',
    scanSourceManual: 'تم التحقق بالرمز اليدوي.',
    scanSourceCamera: 'تم التحقق بالمسح من الكاميرا.',
    cameraNotSupported: 'الوصول للكاميرا غير مدعوم في هذا المتصفح.',
    barcodeNotSupported: 'هذا المتصفح لا يستطيع مسح رموز QR بالكاميرا. استخدم رمز التذكرة اليدوي.',
    cameraPermissionDenied: 'تم رفض إذن الكاميرا أو تعذر تشغيلها.',
    scannerCameraReadError: 'توقف ماسح الكاميرا لأن قارئ QR لم يستطع معالجة الفيديو.',
    organizerApplication: 'طلب منظم',
    organizerApplicationSubtitle: 'للأندية والأقسام والوحدات الجامعية التي ترغب في نشر الفعاليات.',
    organizationName: 'اسم الجهة',
    officialEmail: 'البريد الرسمي',
    advisorName: 'اسم المشرف / المستشار',
    verificationDocument: 'مستند التحقق',
    createPassword: 'إنشاء كلمة مرور',
    confirmPassword: 'تأكيد كلمة المرور',
    confirmPasswordPlaceholder: 'أكد كلمة المرور',
    notes: 'ملاحظات',
    cancel: 'إلغاء',
    requiredFields: 'يرجى تعبئة كل الحقول المطلوبة.',
    pdfRequired: 'يجب أن يكون مستند التحقق بصيغة PDF.',
    passwordMismatch: 'تأكيد كلمة المرور غير مطابق.',
    club: 'نادي',
    department: 'قسم',
    unit: 'وحدة',
    technology: 'تقنية',
    loginTitle: 'تسجيل الدخول إلى KFUPMEvents',
    loginSubtitle: 'استخدم بيانات حسابك الجامعي للمتابعة',
    kfupmEmail: 'بريد جامعة الملك فهد',
    emailPlaceholder: 'your.name@kfupm.edu.sa',
    password: 'كلمة المرور',
    passwordPlaceholder: 'أدخل كلمة المرور',
    universityAccount: 'استخدم حسابك الجامعي',
    forgotPassword: 'نسيت كلمة المرور؟',
    passwordResetSoon: 'رابط إعادة تعيين كلمة المرور سيكون متاحًا بعد ربط الخلفية.',
    quickDemoLogin: 'دخول تجريبي سريع',
    loginAsAttendee: 'الدخول كحاضر',
    loginAsOrganizer: 'الدخول كمنظم',
    loginAsAdmin: 'الدخول كمدير',
    organizerApplyCta: 'منظم جديد؟ قدّم طلب صلاحيات منظم',
    invalidEmail: 'أدخل بريدًا صحيحًا من جامعة الملك فهد.',
    weakPassword: 'كلمة المرور يجب أن تكون 8 أحرف على الأقل وتحتوي على حروف وأرقام.',
    noAccountFound: 'لا يوجد حساب لهذا البريد.',
    accountDisabled: 'هذا الحساب معطل حالياً.',
    invalidCredentials: 'البريد أو كلمة المرور غير صحيحة.',
    signedInSuccessfully: 'تم تسجيل الدخول بنجاح.',
    signedInAs: 'تم تسجيل الدخول كـ',
    ticketReserved: 'تم حجز التذكرة بنجاح.',
    bookingCancelled: 'تم إلغاء الحجز.',
    eventUpdated: 'تم تحديث الفعالية.',
    draftSaved: 'تم حفظ المسودة.',
    eventSubmitted: 'تم إرسال الفعالية للموافقة.',
    eventApproved: 'تم قبول الفعالية.',
    eventRejected: 'تم رفض الفعالية.',
    eventDeleted: 'تم حذف الفعالية.',
    applicationApproved: 'تم قبول الطلب.',
    applicationRejected: 'تم رفض الطلب.',
    adminCannotDemote: 'لا يمكن للمدير تخفيض دور الحساب الحالي.',
    userRoleUpdated: 'تم تحديث دور المستخدم.',
    adminCannotBanSelf: 'لا يمكن للمدير حظر الحساب الحالي.',
    userStatusUpdated: 'تم تحديث حالة المستخدم.',
    organizerApplicationSubmitted: 'تم إرسال طلب المنظم.',
    checkedInSuccess: 'تم تسجيل الحضور بنجاح.',
    view: 'عرض',
    edit: 'تعديل',
    menu: 'القائمة',
    eventShortcuts: 'اختصارات الفعاليات',
    openMenu: 'فتح القائمة',
    switchLanguage: 'تغيير اللغة',
    imageFileError: 'يرجى اختيار ملف صورة لغلاف الفعالية.',
    completeBasicInfo: 'أكمل كل حقول المعلومات الأساسية المطلوبة.',
    completeSchedule: 'أكمل كل حقول الجدول المطلوبة.',
    completeTicketPolicy: 'السعة والحد لكل مستخدم وسياسة الفعالية مطلوبة.'
  }
};

const eventTranslations = {
  ar: {
    'evt-1': {
      title: 'ورشة الذكاء الاصطناعي وتعلم الآلة',
      description: 'تعلّم أساسيات الذكاء الاصطناعي وتعلم الآلة من خلال تطبيقات عملية.',
      longDescription: 'ورشة جامعية عملية للطلاب المهتمين بفهم أساسيات تعلم الآلة وتطبيقها على مشكلات واقعية.',
      organizerName: 'نادي التقنية بجامعة الملك فهد',
      location: 'مبنى 22، قاعة 301',
      policy: 'يجب على الحضور إحضار أجهزتهم المحمولة. لا يمكن الإلغاء بعد الموعد المحدد.'
    },
    'evt-2': {
      title: 'يوم المهنة بجامعة الملك فهد 2026',
      description: 'قابل جهات التوظيف واستكشف فرص التدريب والعمل.',
      longDescription: 'يربط يوم المهنة السنوي طلاب جامعة الملك فهد بجهات التوظيف من مختلف القطاعات.',
      organizerName: 'إدارة خدمات التوظيف',
      location: 'ساحة الجامعة',
      policy: 'ينبغي على الطلاب إحضار السيرة الذاتية والبطاقة الجامعية.'
    },
    'evt-3': {
      title: 'المهرجان الثقافي: ليلة التراث السعودي',
      description: 'احتفاء بالثقافة السعودية مع عروض وأطعمة ومعارض تراثية.',
      longDescription: 'أمسية مفتوحة للاحتفاء بالتراث تتضمن عروضاً طلابية وأركاناً ثقافية وتجارب تفاعلية.',
      organizerName: 'الجمعية الثقافية بجامعة الملك فهد',
      location: 'المسرح الرئيسي',
      policy: 'فعالية مناسبة للعائلات. تفتح الأبواب قبل الموعد بنصف ساعة.'
    },
    'evt-4': {
      title: 'مسابقة عروض الشركات الناشئة',
      description: 'اعرض فكرتك أمام لجنة مستثمرين واربح فرص تمويل وإرشاد.',
      longDescription: 'يعرض الطلاب المؤسسون أفكارهم أمام لجنة تحكيم من الصناعة وبرامج ريادة الأعمال.',
      organizerName: 'مركز ريادة الأعمال',
      location: 'مركز الابتكار',
      policy: 'ينبغي على الفرق الحضور قبل أول عرض بـ45 دقيقة.'
    },
    'evt-5': {
      title: 'اليوم الرياضي السنوي',
      description: 'يوم كامل من الأنشطة الرياضية يشمل كرة القدم والسلة وألعاب القوى.',
      longDescription: 'تنظم إدارة الرياضة مهرجاناً رياضياً كاملاً مع بطولات ودية وجوائز للفرق الفائزة.',
      organizerName: 'إدارة الرياضة بجامعة الملك فهد',
      location: 'المجمع الرياضي',
      policy: 'أحضر ملابس رياضية وبطاقتك الجامعية.'
    },
    'evt-6': {
      title: 'معسكر الأمن السيبراني',
      description: 'معسكر مكثف لمدة ثلاثة أيام حول الاختراق الأخلاقي وأمن الشبكات والاستجابة للحوادث.',
      longDescription: 'معسكر مخصص للطلاب المهتمين بعمليات الأمن السيبراني والأدوات الدفاعية.',
      organizerName: 'نادي الأمن السيبراني بجامعة الملك فهد',
      location: 'معمل الحاسب B15',
      policy: 'يفضل وجود معرفة أساسية بنظام لينكس. المقاعد ممتلئة في بيانات العرض.'
    },
    'evt-7': {
      title: 'ندوة التوعية البيئية',
      description: 'مسودة ندوة حول مبادرات الاستدامة في الحرم الجامعي.',
      longDescription: 'فعالية تجريبية لعرض سير عمل المنظم وتعديل الفعاليات.',
      organizerName: 'نادي الروبوتات بجامعة الملك فهد',
      location: 'مبنى 11، قاعة 2',
      policy: 'فعالية مسودة لتجربة تعديل المنظم.'
    },
    'evt-8': {
      title: 'ورشة البلوك تشين والعملات الرقمية',
      description: 'فعالية معلقة توضح عملية مراجعة الإدارة قبل النشر.',
      longDescription: 'فعالية تجريبية معلقة مستخدمة في قائمة مراجعة المدير.',
      organizerName: 'نادي التقنية المالية بجامعة الملك فهد',
      location: 'مبنى 58، معمل 4',
      policy: 'بانتظار موافقة الإدارة.'
    }
  }
};

const readStoredLanguage = () => {
  if (typeof window === 'undefined') return 'en';
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return stored === 'ar' ? 'ar' : 'en';
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(readStoredLanguage);
  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    if (typeof document === 'undefined') return;
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [direction, language]);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(() => {
    const t = (key) => translations[language][key] || translations.en[key] || key;
    const categoryLabel = (category) => {
      const map = {
        Workshop: t('workshops'),
        Career: t('career'),
        Cultural: t('cultural'),
        Competition: t('competition'),
        Sports: t('sports'),
        Seminar: t('seminar')
      };
      return map[category] || category;
    };
    const statusLabel = (status) => {
      const map = {
        approved: language === 'ar' ? 'مقبولة' : 'approved',
        pending: language === 'ar' ? 'معلقة' : 'pending',
        draft: language === 'ar' ? 'مسودة' : 'draft',
        rejected: language === 'ar' ? 'مرفوضة' : 'rejected',
        cancelled: language === 'ar' ? 'ملغاة' : 'cancelled',
        confirmed: language === 'ar' ? 'مؤكدة' : 'confirmed',
        attendee: t('attendee'),
        organizer: t('organizer'),
        admin: t('admin')
      };
      return map[status] || status;
    };
    const eventText = (event, field) => {
      if (!event) return '';
      return eventTranslations[language]?.[event.id]?.[field] || event[field] || '';
    };

    return {
      language,
      direction,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'ar' : 'en')),
      t,
      categoryLabel,
      eventText,
      statusLabel
    };
  }, [direction, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
};
